steps:
- name: google/cloud-sdk:alpine
  id: Clone repo
  entrypoint: git
  args: ['clone', 'https://github.com/amey-shivaami/shweta87790.git']
  dir: '/workspace'
  
- name: 'gcr.io/cloud-builders/kubectl'
  script: gcloud --quiet beta compute --project "internal-pocs-cloud-team" ssh amey@linux-amey1 --command="cd /home/amey/gitActionTest/test/ && rm -r Hello" --zone=asia-south1-c 
  
- name: 'gcr.io/cloud-builders/kubectl'
  script: gcloud compute scp --recurse /workspace/ linux-amey1:/home/amey/gitActionTest/test/ --zone=asia-south1-c
# - name: 'gcr.io/cloud-builders/kubectl'
  # script: gsutil rsync /workspace amey@linux-amey1:/home/amey/gitActionTest/test/

