steps:
- name: google/cloud-sdk:alpine
  id: Clone repo
  entrypoint: git
  args: ['clone', 'https://github.com/amey-shivaami/shweta87790.git']
  dir: '/workspace'
  
- name: 'ubuntu'
  script: ls /workspace

- name: 'deploy'
  env:
    source: '/workspace'
    destination: 'amey@35.200.161.77:/home/amey/gitActionTest/test/'            
    script: |
      echo "${{secrets.DEPLOY_KEY}}" > deploy_key
      chmod 600 ./deploy_key
      sudo rsync -chav --delete \
        -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
        --exclude /sass \
        ${{env.source}} ${{env.destination}} 
