steps:
- name: google/cloud-sdk:alpine
  id: Clone repo
  entrypoint: git
  args: ['clone', 'https://github.com/amey-shivaami/shweta87790.git']
  dir: '/workspace'
  
- name: 'ubuntu'
  script: apt-get update && apt-get install -y rsync

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', 'echo "${secrets.DEPLOY_KEY}" > deploy_key && chmod 600 deploy_key']

- name: 'ubuntu'
  script: rsync -chav --delete -e "ssh -i deploy_key -o StrictHostKeyChecking=no" --exclude /sass /workspace amey@35.200.161.77:/home/amey/gitActionTest/test/
