steps:
- name: google/cloud-sdk:alpine
  id: Clone repo
  entrypoint: git
  args: ['clone', 'https://github.com/amey-shivaami/shweta87790.git']
  dir: '/workspace'
  
- name: 'gcr.io/cloud-builders/kubectl'
  script: gcloud compute scp --recurse /workspace linux-amey1:/home/amey/gitActionTest/test
# - name: 'gcr.io/cloud-builders/kubectl'
  # script: gsutil rsync /workspace amey@linux-amey1:/home/amey/gitActionTest/test/

