name: Deploy Code

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 🔎 Check IP
        run: curl https://api.ipify.org
      - name: Sync Data
        env:
          source: './'
          destination: 'amey@35.200.161.77:/home/amey/gitActionTest/test/'          
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          sudo rsync -chav --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /sass \
            ${{env.source}} ${{env.destination}}
